---
- name: site
  hosts: webservers:mappers:reducers
  vars_files:
  - cluster_config.yaml
  remote_user: ec2-user
  tasks:
  - name: install packages
    yum: name={{ item }} state=latest
    with_items:
      - git
      - geos-devel
    become: yes

  - name: install python packages
    environment:
      PATH: /usr/local/bin/:$PATH
    pip: name={{ item }} state=latest
    with_items:
      - pandas
      - shapely
    become: yes

  - name: deploy SSH key
    s3:
      bucket: "{{ deploy_bucket }}"
      object: "/aws/{{ deploy_key }}"
      dest: "{{ deploy_home }}/.ssh/{{ deploy_key }}"
      overwrite: no
      mode: get

  - name: set SSH key mode
    file:
      path: "{{ deploy_home }}/.ssh/{{ deploy_key }}"
      mode: 0600
    become: yes

  - name: deploy project repository
    git:
      repo: "{{ repo_url }}"
      dest: "{{ repo_home }}"
      version: master # TODO: change to your branch
      key_file: "{{ deploy_home }}/.ssh/{{ deploy_key }}"
      accept_hostkey: yes
      update: yes

- name: webservers
  hosts: webservers
  vars_files:
  - cluster_config.yaml
  remote_user: "{{ deploy_user }}"
  tasks:
  - name: ensure apache is at the latest version
    yum: name=httpd state=latest
    notify:
      - restart apache
    become: yes

  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
    become: yes

  - name: setup homepage
    shell: "echo {{ inventory_hostname }} > /var/www/html/index.html"
    args:
      creates: "/var/www/html/index.html"
    become: yes

  - name: setup sub homepage
    shell: "echo {{ inventory_hostname }} > /var/www/html/{{ inventory_hostname_short }}/index.html"
    args:
      creates: "/var/www/html/{{ inventory_hostname_short }}/index.html"
    become: yes

  - name: start bokeh
    shell: "bokeh serve taxi --host web.bittiger.info:5006 &>bokeh-`date +%Y-%m-%d-%H-%M-%S`.log &"
    args:
      chdir: "{{ repo_home }}"
    async: 10
    poll: 0

  handlers:
  - name: restart apache
    service: name=httpd state=restarted
    become: yes
