---
deploy_user: ec2-user
deploy_key: id_bitbucket_deploy
deploy_home: "/home/{{ deploy_user }}"
deploy_bucket: dun-us-west-2
repo_url: git@bitbucket.org:bittiger-aws/aws.git
repo_home: "{{ deploy_home }}/aws"
