---
- hosts: webserver
  vars:
    http_port: 80
    max_clients: 200
    deploy_user: ec2-user
    deploy_key: id_bitbucket_deploy
    url: web.bitiger.info:5006
  remote_user: ec2-user
  tasks:
  - name: install packages
    yum: name={{ item }} state=latest
    with_items:
      - git
      - geos-devel
    become: yes

  - name: intall python packages
    environment:
      PATH: /usr/local/bin/:$PATH
    pip: name={{ item }} state=latest
    with_items:
      - pandas
      - shapely
    become: yes

  - name: ensure apache is at the latest version
    yum: name=httpd state=latest
    notify:
      - restart apache
    become: yes

  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
    become: yes

  - name: deploy bitbucket SSH key
    copy:
      src: ~/.ssh/{{ deploy_key }}
      dest: /home/{{ deploy_user }}/.ssh/{{ deploy_key }}
      owner: "{{ deploy_user }}"
      mode: 0400

  - name: deploy project repository
    git:
      repo: git@bitbucket.org:bittiger-aws/aws.git
      dest: /home/{{ deploy_user }}/aws
      key_file: /home/{{ deploy_user }}/.ssh/{{ deploy_key }}
      accept_hostkey: yes
      update: yes

  - name: start bokeh
    shell: "bokeh serve taxi --host web.bittiger.info:5006 &>bokeh-`date +%Y-%m-%d-%H-%M-%S`.log &"
    args:
      chdir: /home/{{ deploy_user }}/aws
    async: 10
    poll: 0

  handlers:
    - name: restart apache
      service: name=httpd state=restarted
      become: yes
